---
title: "GameLib Database"
---

erDiagram
    Game o{--o{ Genre: "belongs to"
    Game o{--o{ Platform: "belongs to"
    Game o{--o{ Tag: "has"

    Game {
        int Id
        string Title
        int ReleaseYear
        string CoverImage
        string Description
        int Rating
        boolean IsFavorited
        int RawgId
        int GenreID
        int PlatformID
    }

    Tag {
        int Id
        string TagName
    }

    Genre {
        int Id
        string GenreName
    }

    Platform {
        int Id
        string PlatformName
    }

    Settings {
        int Id
        string SettingName
        string SettingValue
    }